Final Changes
abdulrahmanshr75/My-portfolio pull request #1
Opened 2021-11-24 18:49 UTC by abdulrahmanshr75

Fixed linters
changed screenshot type from png to jpg
please review my code
thank you

2021-11-24 21:07 UTC, Gambit142 reviewed
Hi @abdulrahmanshr75  👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-11-24 22:46 UTC, alonsofl requested changes
Hi @abdulrahman75,

You have done a great job so far! :muscle:
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] I think it could be a good idea to be more descriptive with the PR title and description. Remember that when working with teams we have to deal with timezones and being descriptive could save time. Please, update your PR title and description to give more information about the changes introduced :pushpin: :wink: 

_Check the comments under the review._

## To highlight :dart:
- Linters working correctly :heavy_check_mark:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-24 22:46 UTC, alonsofl commented on Readme.md
> +![screenshot](./images/port.png)
- [ ] You have done an excellent job with your project :muscle: but I would suggest updating the screenshot path because it's showing a broken image. Please, fix this to make your README even better :wink:
![image](https://user-images.githubusercontent.com/81522435/143319208-c11f98fd-353f-4adc-b75e-23c97fdf6e47.png)

2021-11-24 22:46 UTC, alonsofl commented on Readme.md
> +[Live Demo Link](https://livedemo.com)
- [ ] I think you could delete the sections that you are not using like in this situation. It is a good practice to maintain your README up to date. Please, update or delete this "Live Demo" section :raised_hands:

2021-11-24 22:46 UTC, alonsofl commented on index.html
> +        </nav>
- [ ] I would suggest moving this `<nav>` tag inside the `<header>` tag. Remember that we are on the mobile version milestone (and it is a mobile-version project) and first you have to make sure that your mobile version looks good (after that we will work on the desktop version :wink:)
- [ ] Also, you are missing the "Logo" aligned to the left to match the Figma design. Please, add this main logo/text to make your portfolio even better :hugs:

  Your design:
  ![image](https://user-images.githubusercontent.com/81522435/143320839-4d6f5257-6c10-4d2f-a262-083f7a9123a4.png)

  Figma design:
  ![image](https://user-images.githubusercontent.com/81522435/143320857-c7c7e5b7-1862-458f-9182-e0aec917fc43.png)

2021-11-24 22:46 UTC, alonsofl commented on index.html
> +            </p>
- [ ] I think there is an issue with your headline text because it is a requirement to match the Figma design. Please, update the `font-family`, `font-size`, `font-weight` and layout/spacing. You can find all this information to the right side of the elements in Figma :wink:
![image](https://user-images.githubusercontent.com/81522435/143321168-4945cf26-6caa-4bb1-97fd-b654c7ea630e.png)

  Your design:
  ![image](https://user-images.githubusercontent.com/81522435/143321188-2967bdb7-3a9f-43e1-b51e-db8ad89e6618.png)

  Figma design:
  ![image](https://user-images.githubusercontent.com/81522435/143321220-2aafd198-ebee-4210-a864-a9bf60afbd9e.png)

2021-11-24 22:46 UTC, alonsofl commented on index.html
> +            <a class="button" href="#contact">Lets Connect</a>
- [ ] It is a requirement to match the Figma design and this button is not present in the reference. Please, remove this button in order to match the template :raised_hands:

  Your design:
  ![image](https://user-images.githubusercontent.com/81522435/143321455-4bb77a40-116b-485d-8c65-d5d45a818970.png)

  Figma design:
  ![image](https://user-images.githubusercontent.com/81522435/143321477-32e8e59a-47a4-483b-999b-fa3a3bd848fd.png)

2021-11-24 22:46 UTC, alonsofl commented on index.html
> +            </div>
- [ ]  I would suggest using the `<ul>` tag (unordered list) instead of the `<div>` and remember that each "item" should be inside of the `<li>` tag (list item). Remember that the `<ul>` tag (unordered list) is the semantically correct way to "list" things like links, cards, etc. You can see more information [here](https://www.w3schools.com/tags/tag_ul.asp) :wink:
![image](https://user-images.githubusercontent.com/81522435/143321682-2c637720-f659-4e6c-819f-a7c2cda6d11b.png)

- [ ] There is an issue with your social media icons because these are not matching the Figma design. I would suggest fixing this to make your mobile version look better :wink:

  Your design:
  ![image](https://user-images.githubusercontent.com/81522435/143321885-9819a24b-8ba4-43b5-895f-d9bc410bd44e.png)

  Figma design:
  ![image](https://user-images.githubusercontent.com/81522435/143321910-05631a7a-4586-419e-9925-600ae2d769ce.png)

2021-11-25 09:00 UTC, Cathella requested changes
## Hi @abdulrahmanshr75 👋🏻, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-25 09:00 UTC, Cathella commented on index.html
> +            </ul>
- [ ] Please remove this part code from the header because it is not part of the requirements needed for this project.
- [ ] The header structure should only hold the logo that should be enclosed in an <a> tag and the menu icon button. The structure should be as below.
```
<header>
  <a href="#"> -- logo goes here --</a>
  <nav>-- menu icon goes here --</nav>
</header>
```

2021-11-25 09:00 UTC, Cathella commented on index.html
> +            </div>
- [ ] As suggested by the previous reviewer, please work on implementing the above change.
The code structure should look as below
```
<ul>
  <li><a href="#"> -- icon goes here -- </a></li>
  <li><a href="#"> -- icon goes here -- </a></li>
  <li><a href="#"> -- icon goes here -- </a></li>
  <li><a href="#"> -- icon goes here -- </a></li>
  <li><a href="#"> -- icon goes here -- </a></li>
</ul>
```

- [ ] Please remember to include all the icons in their specified color as show in the design
<img width="318" alt="ic" src="https://user-images.githubusercontent.com/4247740/143408277-b09aba26-4c46-44ef-8480-4360a9c7a81c.PNG">

2021-11-25 09:00 UTC, Cathella commented on style.css
> +
- [ ] We don't currently need to write any media queries. I request that you implement the Figma design as it is.
Your mobile design does not conform to the project specifications.
### Your design
![Screenshot 2021-11-25 at 11-49-06 Abdulrahman Shrshar Portifolio](https://user-images.githubusercontent.com/4247740/143409468-5e6ec850-8e89-49da-b1ce-4b48df345434.png)

### Your design on a smaller width

![Screenshot 2021-11-25 at 11-51-37 Abdulrahman Shrshar Portifolio](https://user-images.githubusercontent.com/4247740/143409712-96f19da9-f307-4491-8c5c-1170a5e50409.png)

### How it should look like

- [ ] Please checkout the design [here](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A988)

2021-11-25 11:02 UTC, mmsesay requested changes
Hi @abdulrahmanshr75 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-25 11:02 UTC, mmsesay commented
- [ ] Please check out your design. It's not aligned with the Figma design. I believe we can get this fix.

**Note: Please do not try to replicate the purple and blue squares around the contents shown in the Figma.** 
Those shapes are Figma's user selections.  

Your Design                                                        |  Figma Design                                  |
:-------------------------------------------------------------:|:-----------------------------------------------:|
![Your Design](https://user-images.githubusercontent.com/39523312/143427814-7141fd4f-e1b0-4146-87ac-54d026e64f0c.png)   |  ![Figma Design](https://user-images.githubusercontent.com/39523312/143427830-dfa45bf0-e1ce-4c71-b7b9-f0ac63955ba4.png)|

2021-11-25 11:04 UTC, mmsesay commented
- [ ] [OPTIONAL] Your project is having some conflicts. I suggest you try fixing them also.

2021-11-25 14:05 UTC, closed without merging